# TODO instead of using this list of urls (which was generated by a curl and
# some regex...) get the list of files automatically. Switch to rsync when rsync
# starts working :)
f = File.open('govtrack_data_urls.txt')
f.each_line do |line|
  bill = line.split('/').last.strip
  folder = "govtrack_data/2013_votes/#{bill}"
  `mkdir #{folder}`
  `curl #{line.strip}/data.json > #{folder}/data.json`
end
